---
services:
  windrose:
    image: indifferentbroccoli/windrose-server-docker
    platform: linux/amd64
    restart: unless-stopped
    container_name: windrose
    stop_grace_period: 30s
    ports:
      - '7777:7777/tcp' # If using direct connection
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/server-files
